# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-03-25 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('picture_of_the_day', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='potd',
            name='retrieved_from_source_url_at',
        ),
        migrations.AddField(
            model_name='potd',
            name='detail_url',
            field=models.URLField(blank=True, editable=False, help_text='URL for additional information, e.g. a wikipedia article corresponding to the image', verbose_name='detail url'),
        ),
        migrations.AddField(
            model_name='potd',
            name='retrieved_from_source_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='datetime retrieved from source'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='potd',
            name='source_url',
            field=models.URLField(blank=True, editable=False, help_text='URL for the image page, e.g. the wikimedia commons page', verbose_name='source url'),
        ),
        migrations.AlterField(
            model_name='potd',
            name='potd_at',
            field=models.DateField(db_index=True, verbose_name='date featured as picture of the day'),
        ),
        migrations.AlterField(
            model_name='potd',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=100),
        ),
    ]
