# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-03-25 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import picture_of_the_day.models


class Migration(migrations.Migration):

    dependencies = [
        ('picture_of_the_day', '0002_auto_20170325_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='potd',
            name='image_url',
            field=models.URLField(blank=True, editable=False, help_text='URL for the direct link to the image', verbose_name='image url'),
        ),
        migrations.AlterField(
            model_name='potd',
            name='image',
            field=models.ImageField(blank=True, height_field='height', upload_to=picture_of_the_day.models.image_upload_path, verbose_name='picture of the day image file', width_field='width'),
        ),
    ]
