# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture_of_the_day', '0004_potd_image_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='potd',
            name='copyright_info',
            field=models.TextField(blank=True, verbose_name='copyright information'),
        ),
        migrations.AlterField(
            model_name='potd',
            name='source_type',
            field=models.CharField(choices=[('unspecified', 'Unspecified source'), ('wikipedia_en', 'Wikipedia (English)'), ('nasa_apod_en', 'NASA Astronomy Picture of the Day (English)')], default='unspecified', max_length=36),
        ),
    ]
